package zxf.reactor.mono;

/*
    Mono.empty()
    Mono.never()
    Mono.just...
    Mono.error...
    Mono.from...
    Mono.zip...
    Mono.delay...
    Mono.defer...
    Mono.create(...)
    Mono.firstWith...
    Mono.ignoreElements(...)
    Mono.sequenceEqual...
    Mono.using...
    Mono.when...
 */
public class MonoCreateTests {

}
