package zxf.reactor.mono;

/*
    mono.map...
    mono.then...
    mono.flatMap...
    mono.filter...
    mono.concatWith...
    mono.mergeWith...
    mono.cache...
    mono.zipWith...
 */
public class MonoOperationTests {
}
